//
//  File.swift
//  
//
//  Created by Imthath on 5/19/21.
//

import Foundation

class SurahsArabic: SurahName {
  var surah0: String { "الفاتحة" }
  var surah1: String { "البقرة" }
  var surah2: String { "آل عمران" }
  var surah3: String { "النساء" }
  var surah4: String { "المائدة" }
  var surah5: String { "اﻷنعام" }
  var surah6: String { "اﻷعراف" }
  var surah7: String { "اﻷنفال" }
  var surah8: String { "التوبة" }
  var surah9: String { "يونس" }
  var surah10: String { "هود" }
  var surah11: String { "يوسف" }
  var surah12: String { "الرعد" }
  var surah13: String { "إبراهيم" }
  var surah14: String { "الحجر" }
  var surah15: String { "النحل" }
  var surah16: String { "اﻹسراء" }
  var surah17: String { "الكهف" }
  var surah18: String { "مريم" }
  var surah19: String { "طه" }
  var surah20: String { "اﻷنبياء" }
  var surah21: String { "الحج" }
  var surah22: String { "المؤمنون" }
  var surah23: String { "النور" }
  var surah24: String { "الفرقان" }
  var surah25: String { "الشعراء" }
  var surah26: String { "النمل" }
  var surah27: String { "القصص" }
  var surah28: String { "العنكبوت" }
  var surah29: String { "الروم" }
  var surah30: String { "لقمان" }
  var surah31: String { "السجدة" }
  var surah32: String { "اﻷحزاب" }
  var surah33: String { "سبأ" }
  var surah34: String { "فاطر" }
  var surah35: String { "يس" }
  var surah36: String { "الصافات" }
  var surah37: String { "ص" }
  var surah38: String { "الزمر" }
  var surah39: String { "غافر" }
  var surah40: String { "فصلت" }
  var surah41: String { "الشورى" }
  var surah42: String { "الزخرف" }
  var surah43: String { "الدخان" }
  var surah44: String { "الجاثية" }
  var surah45: String { "اﻷحقاف" }
  var surah46: String { "محمد" }
  var surah47: String { "الفتح" }
  var surah48: String { "الحجرات" }
  var surah49: String { "ق" }
  var surah50: String { "الذاريات" }
  var surah51: String { "الطور" }
  var surah52: String { "النجم" }
  var surah53: String { "القمر" }
  var surah54: String { "الرحمن" }
  var surah55: String { "الواقعة" }
  var surah56: String { "الحديد" }
  var surah57: String { "المجادلة" }
  var surah58: String { "الحشر" }
  var surah59: String { "الممتحنة" }
  var surah60: String { "الصف" }
  var surah61: String { "الجمعة" }
  var surah62: String { "المنافقون" }
  var surah63: String { "التغابن" }
  var surah64: String { "الطلاق" }
  var surah65: String { "التحريم" }
  var surah66: String { "الملك" }
  var surah67: String { "القلم" }
  var surah68: String { "الحاقة" }
  var surah69: String { "المعارج" }
  var surah70: String { "نوح" }
  var surah71: String { "الجن" }
  var surah72: String { "المزمل" }
  var surah73: String { "المدثر" }
  var surah74: String { "القيامة" }
  var surah75: String { "اﻹنسان" }
  var surah76: String { "المرسلات" }
  var surah77: String { "النبأ" }
  var surah78: String { "النازعات" }
  var surah79: String { "عبس" }
  var surah80: String { "التكوير" }
  var surah81: String { "الانفطار" }
  var surah82: String { "المطففين" }
  var surah83: String { "الانشقاق" }
  var surah84: String { "البروج" }
  var surah85: String { "الطارق" }
  var surah86: String { "اﻷعلى" }
  var surah87: String { "الغاشية" }
  var surah88: String { "الفجر" }
  var surah89: String { "البلد" }
  var surah90: String { "الشمس" }
  var surah91: String { "الليل" }
  var surah92: String { "الضحى" }
  var surah93: String { "الشرح" }
  var surah94: String { "التين" }
  var surah95: String { "العلق" }
  var surah96: String { "القدر" }
  var surah97: String { "البينة" }
  var surah98: String { "الزلزلة" }
  var surah99: String { "العاديات" }
  var surah100: String { "القارعة" }
  var surah101: String { "التكاثر" }
  var surah102: String { "العصر" }
  var surah103: String { "الهمزة" }
  var surah104: String { "الفيل" }
  var surah105: String { "قريش" }
  var surah106: String { "الماعون" }
  var surah107: String { "الكوثر" }
  var surah108: String { "الكافرون" }
  var surah109: String { "النصر" }
  var surah110: String { "المسد" }
  var surah111: String { "اﻹخلاص" }
  var surah112: String { "الفلق" }
  var surah113: String { "الناس" }
}
